language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
notifications:
  email:
    on_success: never
script: "npm run-script test-travis"
after_script: "cat ./coverage/lcov.info | coveralls"
